In [17]:
from __future__ import print_function
from IPython import display
import tensorflow as tf
import numpy as np
from tensorflow.python.data import Dataset
import pandas as pd

try:
    tf.contrib.eager.enable_eager_execution()
    print("TF imported with eager execution!")
except ValueError:
    print("TF already imported with eager execution!")


TF imported with eager execution!


# 张量运算相关函数

In [5]:
# 定义常量
a = tf.constant([1, 2, 3], dtype=tf.int32)
print(a)
# tf.Tensor([1 2 3], shape=(3,), dtype=int32)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [6]:
# 创建指定纬度数据, 以 1 填充
print(tf.ones([6]))
print(tf.ones([3, 2]))

tf.Tensor([1. 1. 1. 1. 1. 1.], shape=(6,), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [7]:
# 创建指定纬度数据, 以 0 填充
print(tf.zeros([6]))
print(tf.zeros([3, 2]))


tf.Tensor([0. 0. 0. 0. 0. 0.], shape=(6,), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [8]:
# 重置数据的维度
a = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
print(tf.reshape(a, [3, 3]))


tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [9]:
# 随机数 - 正态分布
print(tf.random_normal(shape=[10], mean=2.0, stddev=1.0))

tf.Tensor(
[1.5436863 2.9982014 2.9637558 2.1490326 1.9388257 2.571524  0.8946587
 2.3943443 1.0879513 1.0494789], shape=(10,), dtype=float32)


In [10]:
# 随机数 - 范围随机
print(tf.random_uniform(shape=[5, 5], minval=50, maxval=100))


tf.Tensor(
[[82.598724 90.53528  75.95274  77.61642  86.012886]
 [53.618168 90.59499  92.60213  78.02025  81.80449 ]
 [60.031307 74.45615  79.75863  95.69632  91.88367 ]
 [50.543964 97.603516 64.23519  91.58482  56.42457 ]
 [81.66092  79.993454 88.58026  65.41999  75.83295 ]], shape=(5, 5), dtype=float32)


In [19]:
# 数据拼接成多维
d1 = tf.random_uniform([10, 1], 0, 10)
d2 = tf.random_uniform([10, 1], 0, 10)
d3 = tf.add(d1,d2)
result = tf.concat([d1,d2,d3], axis=1)
print("d1:", d1)
print("d2:", d2)
print("d3:", d3)
print("result:", result)

d1: tf.Tensor(
[[0.29824257]
 [4.243346  ]
 [9.39332   ]
 [6.6800904 ]
 [2.3734176 ]
 [4.1688194 ]
 [4.6724296 ]
 [7.3838615 ]
 [5.703574  ]
 [9.930505  ]], shape=(10, 1), dtype=float32)
d2: tf.Tensor(
[[5.976689 ]
 [4.984765 ]
 [2.5285149]
 [6.8168283]
 [8.147064 ]
 [2.3720598]
 [8.96068  ]
 [5.477866 ]
 [4.928857 ]
 [4.720149 ]], shape=(10, 1), dtype=float32)
d3: tf.Tensor(
[[ 6.2749314]
 [ 9.228111 ]
 [11.921835 ]
 [13.496919 ]
 [10.520482 ]
 [ 6.5408792]
 [13.63311  ]
 [12.861728 ]
 [10.632431 ]
 [14.650654 ]], shape=(10, 1), dtype=float32)
result: tf.Tensor(
[[ 0.29824257  5.976689    6.2749314 ]
 [ 4.243346    4.984765    9.228111  ]
 [ 9.39332     2.5285149  11.921835  ]
 [ 6.6800904   6.8168283  13.496919  ]
 [ 2.3734176   8.147064   10.520482  ]
 [ 4.1688194   2.3720598   6.5408792 ]
 [ 4.6724296   8.96068    13.63311   ]
 [ 7.3838615   5.477866   12.861728  ]
 [ 5.703574    4.928857   10.632431  ]
 [ 9.930505    4.720149   14.650654  ]], shape=(10, 3), dtype=float32)


In [24]:
datas = pd.DataFrame()
s1 = pd.Series([x for x in np.arange(100)])
datas["index"] = s1
print(datas)


    index
0       0
1       1
2       2
3       3
4       4
5       5
6       6
7       7
8       8
9       9
10     10
11     11
12     12
13     13
14     14
15     15
16     16
17     17
18     18
19     19
20     20
21     21
22     22
23     23
24     24
25     25
26     26
27     27
28     28
29     29
..    ...
70     70
71     71
72     72
73     73
74     74
75     75
76     76
77     77
78     78
79     79
80     80
81     81
82     82
83     83
84     84
85     85
86     86
87     87
88     88
89     89
90     90
91     91
92     92
93     93
94     94
95     95
96     96
97     97
98     98
99     99

[100 rows x 1 columns]


In [33]:
a1 = [x for x in np.arange(10)]
print(a1)
a2 = np.random.permutation(a1)
print(a2)
np.random.shuffle(a1)
print(a1)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[8 0 5 6 3 1 7 9 4 2]
[4, 0, 5, 6, 8, 3, 7, 9, 2, 1]


In [36]:
a1 = [x for x in np.arange(10)]
a1 = np.reshape(a1, [5, 2])
print(a1)
a2 = np.random.permutation(a1)
print(a2)
np.random.shuffle(a1)
print(a1)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[2 3]
 [0 1]
 [6 7]
 [4 5]
 [8 9]]
[[2 3]
 [0 1]
 [6 7]
 [4 5]
 [8 9]]


In [39]:
print(np.random.permutation(np.arange(10)))
print(np.random.shuffle(np.arange(10)))

[6 8 0 7 1 9 4 2 3 5]
None


In [51]:
a1 = np.random.permutation(np.arange(100))
r1 = zip(range(1, 10), range(2, 11))
print(r1)
for rr in r1:
    # rr is tuple
    print(type(rr))
    print("%d to %d" % rr)
    print("r0 = %d, r1 = %d" % (rr[0], rr[1]))


<class 'tuple'>
1 to 2
r0 = 1, r1 = 2
<class 'tuple'>
2 to 3
r0 = 2, r1 = 3
<class 'tuple'>
3 to 4
r0 = 3, r1 = 4
<class 'tuple'>
4 to 5
r0 = 4, r1 = 5
<class 'tuple'>
5 to 6
r0 = 5, r1 = 6
<class 'tuple'>
6 to 7
r0 = 6, r1 = 7
<class 'tuple'>
7 to 8
r0 = 7, r1 = 8
<class 'tuple'>
8 to 9
r0 = 8, r1 = 9
<class 'tuple'>
9 to 10
r0 = 9, r1 = 10


In [60]:
# pd.Series.quantile sample
s1 = pd.Series(np.arange(100))
s1 = s1.append(pd.Series(np.arange(50)))
# print(s1)
r1 = s1.quantile([x for x in np.arange(0.1, 1.1, 0.1)])
print(r1)
print([r1[q] for q in r1.keys()])

0.1     7.0
0.2    14.8
0.3    22.0
0.4    29.6
0.5    37.0
0.6    44.4
0.7    54.3
0.8    69.2
0.9    84.1
1.0    99.0
dtype: float64
[7.0, 14.8, 22.0, 29.6, 37.0, 44.39999999999999, 54.3, 69.2, 84.1, 99.0]
